EXEC usp_AddPlayer 'Miroslava123!', '123M456', 0, 0, 0
EXEC usp_AddPlayer 'Pepi1234', 'otntvanvn', 2, 2, 0
EXEC usp_AddPlayer 'Zhoro', 'Zhorkoeqak', 13, 0, 5
EXEC usp_AddPlayer 'Negreb2026','Negreb1232002', 4, 2, 0
EXEC usp_AddPlayer 'Naiden1998', 'nfog123', 0, 0, 0
EXEC usp_AddPlayer 'Player1', 'Player1', 12, 10, 0
EXEC usp_AddPlayer 'GameSlayer', 'GetGames', 4, 1, 2
EXEC usp_AddPlayer 'HiWorld', 'gameBeast23', 9, 0, 8
EXEC usp_AddPlayer 'WordlEnthusiast', 'wordlislife', 14, 0, 13
EXEC usp_AddPlayer 'HungUp', 'hangman2021', 5, 5, 0

EXEC usp_AddAdmin '#A1Mikaela', 'admins1MI'
EXEC usp_AddAdmin '#A2Petar', 'admins2PD'
EXEC usp_AddAdmin '#A3Zhoro', 'admins3GP'
EXEC usp_AddAdmin '#A4Martin', 'admins4MM'
EXEC usp_AddAdmin '#A5Stoyan', 'admins5StN'

EXEC usp_AddWordHangman 'щастлив', 'лесна'
EXEC usp_AddWordHangman 'такси', 'лесна'
EXEC usp_AddWordHangman 'котка', 'лесна'
EXEC usp_AddWordHangman 'стол', 'лесна'
EXEC usp_AddWordHangman 'спокоен', 'средна'
EXEC usp_AddWordHangman 'шумен', 'средна'
EXEC usp_AddWordHangman 'куче', 'лесна'
EXEC usp_AddWordHangman 'маса', 'лесна'
EXEC usp_AddWordHangman 'мръсен', 'сложна'
EXEC usp_AddWordHangman 'любопитен', 'сложна'
EXEC usp_AddWordHangman 'свеж', 'лесна'
EXEC usp_AddWordHangman 'млад', 'средна'
EXEC usp_AddWordHangman 'тъжен', 'средна'
EXEC usp_AddWordHangman 'велосипед', 'сложна'
EXEC usp_AddWordHangman 'нов', 'лесна'
EXEC usp_AddWordHangman 'нервен', 'сложна'
EXEC usp_AddWordHangman 'безразличен', 'сложна'
EXEC usp_AddWordHangman 'корем', 'средна'
EXEC usp_AddWordHangman 'влак', 'лесна'
EXEC usp_AddWordHangman 'площад', 'средна'
EXEC usp_AddWordHangman 'слънце', 'средна'
EXEC usp_AddWordHangman 'грозен', 'сложна'
EXEC usp_AddWordHangman 'дъжд', 'лесна'
EXEC usp_AddWordHangman 'търпелив', 'средна'
EXEC usp_AddWordHangman 'гръб', 'лесна'
EXEC usp_AddWordHangman 'мотоциклет', 'сложна'
EXEC usp_AddWordHangman 'земя', 'лесна'
EXEC usp_AddWordHangman 'врат', 'лесна'
EXEC usp_AddWordHangman 'небрежен', 'сложна'
EXEC usp_AddWordHangman 'пазар', 'лесна'
EXEC usp_AddWordHangman 'дим', 'лесна'
EXEC usp_AddWordHangman 'кораб', 'лесна'
EXEC usp_AddWordHangman 'внимателен', 'средна'
EXEC usp_AddWordHangman 'неточен', 'сложна'
EXEC usp_AddWordHangman 'цвете', 'лесна'
EXEC usp_AddWordHangman 'празен', 'лесна'
EXEC usp_AddWordHangman 'плаж', 'лесна'
EXEC usp_AddWordHangman 'книга', 'лесна'
EXEC usp_AddWordHangman 'прост', 'средна'
EXEC usp_AddWordHangman 'ходя', 'лесна'

EXEC usp_AddWordWordl 'какво'
EXEC usp_AddWordWordl 'добре'
EXEC usp_AddWordWordl 'много'
EXEC usp_AddWordWordl 'искам'
EXEC usp_AddWordWordl 'знаеш'
EXEC usp_AddWordWordl 'време'
EXEC usp_AddWordWordl 'искаш'
EXEC usp_AddWordWordl 'мисля'
EXEC usp_AddWordWordl 'малко'
EXEC usp_AddWordWordl 'преди'
EXEC usp_AddWordWordl 'хайде'
EXEC usp_AddWordWordl 'някой'
EXEC usp_AddWordWordl 'точно'
EXEC usp_AddWordWordl 'колко'
EXEC usp_AddWordWordl 'човек'
EXEC usp_AddWordWordl 'значи'
EXEC usp_AddWordWordl 'както'
EXEC usp_AddWordWordl 'имаме'
EXEC usp_AddWordWordl 'всеки'
EXEC usp_AddWordWordl 'майка'
EXEC usp_AddWordWordl 'казах'
EXEC usp_AddWordWordl 'никой'
EXEC usp_AddWordWordl 'място'
EXEC usp_AddWordWordl 'прави'
EXEC usp_AddWordWordl 'можем'
EXEC usp_AddWordWordl 'кажеш'
EXEC usp_AddWordWordl 'татко'
EXEC usp_AddWordWordl 'наред'
EXEC usp_AddWordWordl 'доста'
EXEC usp_AddWordWordl 'начин'
EXEC usp_AddWordWordl 'дойде'
EXEC usp_AddWordWordl 'добър'
EXEC usp_AddWordWordl 'нямам'
EXEC usp_AddWordWordl 'после'
EXEC usp_AddWordWordl 'видим'
EXEC usp_AddWordWordl 'правя'
EXEC usp_AddWordWordl 'вечер'
EXEC usp_AddWordWordl 'исках'
EXEC usp_AddWordWordl 'живот'
EXEC usp_AddWordWordl 'чакай'
EXEC usp_AddWordWordl 'какъв'
EXEC usp_AddWordWordl 'стана'
EXEC usp_AddWordWordl 'казва'
EXEC usp_AddWordWordl 'добро'
EXEC usp_AddWordWordl 'измия'
EXEC usp_AddWordWordl 'палто'
EXEC usp_AddWordWordl 'рокля'
EXEC usp_AddWordWordl 'шапка'
EXEC usp_AddWordWordl 'вчера'
EXEC usp_AddWordWordl 'месец'
EXEC usp_AddWordWordl 'книга'
EXEC usp_AddWordWordl 'песен'
EXEC usp_AddWordWordl 'филма'
EXEC usp_AddWordWordl 'играя'
EXEC usp_AddWordWordl 'видях'
EXEC usp_AddWordWordl 'излез'
EXEC usp_AddWordWordl 'влезе'
EXEC usp_AddWordWordl 'народ'
EXEC usp_AddWordWordl 'съдия'
EXEC usp_AddWordWordl 'лекар'
EXEC usp_AddWordWordl 'шефът'
EXEC usp_AddWordWordl 'босът'
